version: '3.2'

services:
  picapport:
    image: patklaey/picapport:8.2.02
    container_name: picapport
    restart: always
    ports:
      - 8080:8080
    volumes:
      - database:/opt/picapport/.picapport/db
      - cache:/opt/picapport/.picapport/cache
      - users:/opt/picapport/.picapport/users
      - "/home/pat/Pictures/Mexiko:/data/Pictures/Mexico"
      - "/home/pat/Pictures/Riga/JPEG:/data/Pictures/Riga"
      - "/home/pat/Pictures/Malaysia/JPEG:/data/Pictures/Malaysia"
      - "/home/pat/Pictures/Helsinki/JPEG:/data/Pictures/Helsinki"
      - "/home/pat/Pictures/New York/New York 1st choice:/data/Pictures/New York"
      - "/home/pat/Pictures/Oman/1. choice:/data/Pictures/Oman"
      - "/home/pat/Pictures/Portugal/1st choice:/data/Pictures/Portugal"
      - "/home/pat/Pictures/SA_2012/1st choice:/data/Pictures/SA_2012"
      - "/home/pat/Pictures/SA_2016/1st choice:/data/Pictures/SA_2016"
      - "/home/pat/Pictures/Stockholm/JPEG:/data/Pictures/Stockholm"
      - "/home/pat/Pictures/General/JPEG:/data/Pictures/General"
      - "/home/pat/Pictures/Sri Lanka/jpg:/data/Pictures/Sri Lanka"
      - "/home/pat/Pictures/New Aruba/JPEG:/data/Pictures/New Aruba"
      - "/home/pat/Pictures/Marrakech/JPEG:/data/Pictures/Marrakech"
      - "/home/pat/Pictures/Sardinien/JPEG:/data/Pictures/Sardinien"
      - "/home/pat/Pictures/Australia_2018/JPEG:/data/Pictures/Australia"
      - "/home/pat/Pictures/Marrakech_2018:/data/Pictures/Marrakech_2018"
      - "/home/pat/Pictures/Maldives/JPEG:/data/Pictures/Maldives"
      - "/home/pat/Pictures/Peru/JPEG:/data/Pictures/Peru"

volumes:
  database:
    driver: local
  cache:
    driver: local
  users:
    driver: local
